### ISSUE TITLE
Test suite takes more than ten seconds to start

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#282] opened 2019-04-27 08:16 UTC
Without any tests:

```
pytest tests/integration/processing/Lexicon.py -k this-is-an-empty-filter
```

this takes about 10-15 seconds to run. It should be less than a second as otherwise test-driven development can't happen.

**Comment by anukul** [comment] 2019-10-21 06:11
Closing, since this is not reproducible at the moment

**Closed by anukul** 2019-10-21 06:11 UTC
